create table category (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table hibernate_sequences (sequence_name varchar(255) not null, next_val bigint, primary key (sequence_name)) engine=InnoDB;
insert into hibernate_sequences(sequence_name, next_val) values ('default',0);
create table jt_instructor (specialization varchar(255), user_id bigint not null, primary key (user_id)) engine=InnoDB;
create table jt_mentor (avg_rating float(23), company varchar(255), user_id bigint not null, primary key (user_id)) engine=InnoDB;
create table jt_ta (avg_rating float(23), no_of_sessions bigint, user_id bigint not null, primary key (user_id)) engine=InnoDB;
create table jt_user (id bigint not null auto_increment, email_id varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
create table ms_instructor (id bigint not null auto_increment, email_id varchar(255), name varchar(255), password varchar(255), specialization varchar(255), primary key (id)) engine=InnoDB;
create table ms_mentor (id bigint not null auto_increment, email_id varchar(255), name varchar(255), password varchar(255), avg_rating float(23), company varchar(255), primary key (id)) engine=InnoDB;
create table ms_ta (id bigint not null auto_increment, email_id varchar(255), name varchar(255), password varchar(255), avg_rating float(23), no_of_sessions bigint, primary key (id)) engine=InnoDB;
create table product (id bigint not null auto_increment, name varchar(255), description varchar(255), image varchar(255), price float(23) not null, category_id bigint, primary key (id)) engine=InnoDB;
create table st_user (discriminator_type integer not null, id bigint not null auto_increment, email_id varchar(255), name varchar(255), password varchar(255), specialization varchar(255), avg_rating float(23), company varchar(255), no_of_sessions bigint, primary key (id)) engine=InnoDB;
create table tpc_instructor (id bigint not null, email_id varchar(255), name varchar(255), password varchar(255), specialization varchar(255), primary key (id)) engine=InnoDB;
create table tpc_mentor (id bigint not null, email_id varchar(255), name varchar(255), password varchar(255), avg_rating float(23), company varchar(255), primary key (id)) engine=InnoDB;
create table tpc_ta (id bigint not null, email_id varchar(255), name varchar(255), password varchar(255), avg_rating float(23), no_of_sessions bigint, primary key (id)) engine=InnoDB;
create table tpc_user (id bigint not null, email_id varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table jt_instructor add constraint FK4od6mbg1v99qri5dtqreaayou foreign key (user_id) references jt_user (id);
alter table jt_mentor add constraint FK74kd6ct4a7jq51dr84f8m7usr foreign key (user_id) references jt_user (id);
alter table jt_ta add constraint FKhq7nv0qp5o8md1xwoglkc7g7k foreign key (user_id) references jt_user (id);
alter table product add constraint FK1mtsbur82frn64de7balymq9s foreign key (category_id) references category (id);
